from __future__ import annotations

FACEBOARD_OBJECT_NAME = "MHC_FaceBoard"
FACEBOARD_COLLECTION_NAME = "MH_FaceBoard"
FACEBOARD_ROOT_BONE = "faceboard_root"
FACEBOARD_WORLD_LOCATION = (0.85, -0.75, 1.02)
FACEBOARD_LAYOUT_SCALE = 0.022
FACEBOARD_BUILD_VERSION = 2
