from __future__ import annotations

# Visible animator controls on the internal body rig.
MAIN_BODY_CONTROLS = {
    "CTRL_root_global",
    "CTRL_pelvis",
    "CTRL_spine_01",
    "CTRL_spine_02",
    "CTRL_spine_03",
    "CTRL_spine_04",
    "CTRL_spine_05",
    "CTRL_neck_01",
    "CTRL_neck_02",
    "CTRL_head",
    "CTRL_clavicle_l",
    "CTRL_upperarm_l",
    "CTRL_lowerarm_l",
    "CTRL_hand_l",
    "CTRL_clavicle_r",
    "CTRL_upperarm_r",
    "CTRL_lowerarm_r",
    "CTRL_hand_r",
    "CTRL_thigh_l",
    "CTRL_calf_l",
    "CTRL_foot_l",
    "CTRL_thigh_r",
    "CTRL_calf_r",
    "CTRL_foot_r",
    "CTRL_hand_ik_l",
    "CTRL_hand_ik_r",
    "CTRL_foot_ik_l",
    "CTRL_foot_ik_r",
    "CTRL_arm_pole_l",
    "CTRL_arm_pole_r",
    "CTRL_leg_pole_l",
    "CTRL_leg_pole_r",
}
